--Tao bang COMPANY 
CREATE TABLE COMPANY
(
	companyNo NUMBER NOT NULL,
	companyName VARCHAR2(50) NOT NULL UNIQUE,
	address VARCHAR2(60),
	hotline VARCHAR2(10),
	gmail VARCHAR2(30),
	startDate DATE,
	accountID NUMBER
);

--Khoa chinh
ALTER TABLE COMPANY ADD CONSTRAINT PK_COMPANY PRIMARY KEY (companyNo);

--Khoa ngoai
ALTER TABLE COMPANY ADD CONSTRAINT FK_COMPANY_ACCOUNT FOREIGN KEY (accountID) REFERENCES ACCOUNT (accountID);

--Du lieu
Insert into COMPANY (COMPANYNO,COMPANYNAME,ADDRESS,HOTLINE,GMAIL,STARTDATE,ACCOUNTID) values (1,'SamSung','Quận 1','2839157310','samsung@gmai.com.vn',to_date('30-JAN-07','DD-MON-RR'),1);
Insert into COMPANY (COMPANYNO,COMPANYNAME,ADDRESS,HOTLINE,GMAIL,STARTDATE,ACCOUNTID) values (2,'Intel','Phú Nhuận','8437363000','Intel@gmai.com.vn',to_date('21-FEB-06','DD-MON-RR'),2);
Insert into COMPANY (COMPANYNO,COMPANYNAME,ADDRESS,HOTLINE,GMAIL,STARTDATE,ACCOUNTID) values (3,'Cocacola','Hải Phòng','0500233891','Cocacola@gmai.com.vn',to_date('14-JUN-96','DD-MON-RR'),3);
Insert into COMPANY (COMPANYNO,COMPANYNAME,ADDRESS,HOTLINE,GMAIL,STARTDATE,ACCOUNTID) values (4,'Petrolimex','Hà Nội','1900363003','Petrolimex@gmai.com.vn',to_date('22-JUN-05','DD-MON-RR'),4);
Insert into COMPANY (COMPANYNO,COMPANYNAME,ADDRESS,HOTLINE,GMAIL,STARTDATE,ACCOUNTID) values (5,'Viettel','Hà Nội','18008098','Viettel@gmai.com.vn',to_date('01-JUN-89','DD-MON-RR'),5);
Insert into COMPANY (COMPANYNO,COMPANYNAME,ADDRESS,HOTLINE,GMAIL,STARTDATE,ACCOUNTID) values (6,'FPT','TP HCM','0962636481','fpt@gmai.com.vn',to_date('03-JUN-89','DD-MON-RR'),6);
