--Tao bang EVALUATE_APL 
CREATE TABLE EVALUATE_APL
(
	companyNo NUMBER NOT NULL,
	applicantNo NUMBER NOT NULL,
	interviewScheduleNo NUMBER NOT NULL,
	mark_apl NUMBER,
	comment_apl VARCHAR2(2000),
	CHECK (mark_apl BETWEEN 1 AND 5)
		 --1: Rat te,
		 --2: Khong hai long,
		 --3: Binh thuong,
		 --4: Hai long,
		 --5: Rat hai long
);

--Khoa chinh
ALTER TABLE EVALUATE_APL ADD CONSTRAINT PK_EVALUATE_APL PRIMARY KEY (companyNo, applicantNo, interviewScheduleNo);

--Khoa ngoai
--Bang EVALUATE_APL
ALTER TABLE EVALUATE_APL ADD CONSTRAINT FK1_EVALUATE_APL FOREIGN KEY (companyNo) REFERENCES COMPANY (companyNo);
ALTER TABLE EVALUATE_APL ADD CONSTRAINT FK2_EVALUATE_APL FOREIGN KEY (applicantNo) REFERENCES APPLICANT (applicantNo);
ALTER TABLE EVALUATE_APL ADD CONSTRAINT FK3_EVALUATE_APL FOREIGN KEY (interviewScheduleNo) REFERENCES INTERVIEW_SCHEDULE (interviewScheduleNo);

--Du lieu
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (1,2,1,5,'Ứng viên trung thực');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (1,3,3,4,'Ứng viên chưa có nhiều kinh nghiệm');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (2,2,2,4,'Ứng viên hơi lúng túng');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (2,4,2,5,'Ứng viên có thực lực');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (2,5,3,5,'Kỹ năng chuyên môn cao');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (3,4,4,3,'Không chuẩn bị chu đáo');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (3,5,2,3,'Thiếu kinh nghiệm chuyên môn');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (3,6,1,3,'Còn nhiều thiếu sót');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (4,7,5,5,'Kỹ năng giao tiếp tốt');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (4,1,1,5,'Kỹ năng giao tiếp kém');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (4,1,2,5,'Thụ động trong trả lời câu hỏi');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (5,7,3,2,'Kỹ năng giao tiếp kém, thụ động');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (5,7,4,2,'Kỹ năng giao tiếp tốt');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (5,7,5,2,'Kỹ năng giao tiếp kém, thụ động');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (6,5,5,4,'Có nhiều trải nghiệm');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (6,6,1,4,'Kinh nghiệm làm việc phong phú');
