--Tao bang HAVE 
CREATE TABLE HAVE
(
	skillNo NUMBER NOT NULL,
	applicantNo NUMBER NOT NULL,
	level_apl NUMBER,
	yearsOfExperience NUMBER,
	CHECK (level_apl BETWEEN 1 AND 6)
		 --1: Kem,
		 --2: Yeu,
		 --3: Trung binh,
		 --4: Kha,
		 --5: Gioi,
		 --6: Chuyen sau
);

--Khoa chinh
ALTER TABLE HAVE ADD CONSTRAINT PK_HAVE PRIMARY KEY (skillNo, applicantNo);

--Khoa ngoai
ALTER TABLE HAVE ADD CONSTRAINT FK1_HAVE FOREIGN KEY (skillNo) REFERENCES SKILL(skillNo);
ALTER TABLE HAVE ADD CONSTRAINT FK2_HAVE FOREIGN KEY (applicantNo) REFERENCES APPLICANT(applicantNo);

--Du lieu
Insert into HAVE (SKILLNO,APPLICANTNO,LEVEL_APL,YEARSOFEXPERIENCE) values (1,4,5,3);
Insert into HAVE (SKILLNO,APPLICANTNO,LEVEL_APL,YEARSOFEXPERIENCE) values (1,3,4,5);
Insert into HAVE (SKILLNO,APPLICANTNO,LEVEL_APL,YEARSOFEXPERIENCE) values (2,2,3,3);
Insert into HAVE (SKILLNO,APPLICANTNO,LEVEL_APL,YEARSOFEXPERIENCE) values (3,4,2,1);
Insert into HAVE (SKILLNO,APPLICANTNO,LEVEL_APL,YEARSOFEXPERIENCE) values (4,5,5,8);
Insert into HAVE (SKILLNO,APPLICANTNO,LEVEL_APL,YEARSOFEXPERIENCE) values (5,1,1,1);
Insert into HAVE (SKILLNO,APPLICANTNO,LEVEL_APL,YEARSOFEXPERIENCE) values (1,1,3,5);
Insert into HAVE (SKILLNO,APPLICANTNO,LEVEL_APL,YEARSOFEXPERIENCE) values (21,1,3,4);
