--Tao bang INTERVIEW_SCHEDULE 
CREATE TABLE INTERVIEW_SCHEDULE
(
	interviewScheduleNo NUMBER NOT NULL,
	startTime DATE,
	endTime DATE,
	location  VARCHAR2(60),
	status NUMBER,
	slot NUMBER,
	interviewerNo NUMBER,
	CHECK (status BETWEEN 0 AND 1)
		-- 0: Chua hoan thanh
		-- 1: Da hoan thanh
);

--Khoa chinh
ALTER TABLE INTERVIEW_SCHEDULE ADD CONSTRAINT PK_INTERVIEW_SCHEDULE PRIMARY KEY (interviewScheduleNo);

--Khoa ngoai
ALTER TABLE INTERVIEW_SCHEDULE ADD CONSTRAINT FK_INTERVIEW_SCHEDULE FOREIGN KEY (interviewerNo) REFERENCES INTERVIEWER (interviewerNo);

--Du lieu
Insert into INTERVIEW_SCHEDULE (INTERVIEWSCHEDULENO,STARTTIME,ENDTIME,LOCATION,STATUS,SLOT,INTERVIEWERNO) values (1,to_date('13-JAN-21','DD-MON-RR'),to_date('15-JAN-21','DD-MON-RR'),'71 Đinh Tiên Hoàng',0,15,1);
Insert into INTERVIEW_SCHEDULE (INTERVIEWSCHEDULENO,STARTTIME,ENDTIME,LOCATION,STATUS,SLOT,INTERVIEWERNO) values (2,to_date('13-FEB-21','DD-MON-RR'),to_date('16-FEB-21','DD-MON-RR'),'65/6 Hà Tôn Quyền',1,17,2);
Insert into INTERVIEW_SCHEDULE (INTERVIEWSCHEDULENO,STARTTIME,ENDTIME,LOCATION,STATUS,SLOT,INTERVIEWERNO) values (3,to_date('26-JAN-21','DD-MON-RR'),to_date('29-JAN-21','DD-MON-RR'),'15 Nguyễn Tri Phương',0,18,2);
Insert into INTERVIEW_SCHEDULE (INTERVIEWSCHEDULENO,STARTTIME,ENDTIME,LOCATION,STATUS,SLOT,INTERVIEWERNO) values (4,to_date('13-JAN-21','DD-MON-RR'),to_date('14-JAN-21','DD-MON-RR'),'72 Ho Tung Mau',0,19,4);
Insert into INTERVIEW_SCHEDULE (INTERVIEWSCHEDULENO,STARTTIME,ENDTIME,LOCATION,STATUS,SLOT,INTERVIEWERNO) values (5,to_date('21-MAR-21','DD-MON-RR'),to_date('24-MAR-21','DD-MON-RR'),'79/5/1 Nguyen Thai Hoc',0,20,5);
