--Tao bang INTERVIEWER 
CREATE TABLE INTERVIEWER
(
	interviewerNo NUMBER NOT NULL,
	interviewerName VARCHAR2(30) NOT NULL,
	phoneNumber VARCHAR2(10),
	gmail VARCHAR2(30),
	companyNo NUMBER,
	accountID NUMBER
);

--Khoa chinh
ALTER TABLE INTERVIEWER ADD CONSTRAINT PK_INTERVIEWER PRIMARY KEY (interviewerNo);

--Khoa ngoai
ALTER TABLE INTERVIEWER ADD CONSTRAINT FK_INTERVIEWER FOREIGN KEY (companyNo) REFERENCES COMPANY (companyNo);
ALTER TABLE INTERVIEWER ADD CONSTRAINT FK_INTERVIEWER_ACCOUNT FOREIGN KEY (accountID) REFERENCES ACCOUNT (accountID);

--Du lieu
Insert into INTERVIEWER (INTERVIEWERNO,INTERVIEWERNAME,PHONENUMBER,GMAIL,COMPANYNO,ACCOUNTID) values (1,'Trần Văn An','0378009008','tranvanan@gmai.com.vn',1,7);
Insert into INTERVIEWER (INTERVIEWERNO,INTERVIEWERNAME,PHONENUMBER,GMAIL,COMPANYNO,ACCOUNTID) values (2,'Trần Văn Bảo','0378989238','tranvanbao@gmai.com.vn',2,8);
Insert into INTERVIEWER (INTERVIEWERNO,INTERVIEWERNAME,PHONENUMBER,GMAIL,COMPANYNO,ACCOUNTID) values (3,'Nguyễn Minh Công','0378011108','nguyenminhcong@gmai.com.vn',3,9);
Insert into INTERVIEWER (INTERVIEWERNO,INTERVIEWERNAME,PHONENUMBER,GMAIL,COMPANYNO,ACCOUNTID) values (4,'Lưu Quốc Anh','0378123097','luuquocanh@gmai.com.vn',4,10);
Insert into INTERVIEWER (INTERVIEWERNO,INTERVIEWERNAME,PHONENUMBER,GMAIL,COMPANYNO,ACCOUNTID) values (5,'Trần Minh Đăng','0374568088','tranminhdang@gmai.com.vn',5,11);
