--Tao bang REQUIRE 
create table REQUIRE (
	positionNo NUMBER NOT NULL,
  	requirementNo NUMBER NOT NULL,
	level_Re NUMBER,
	yearsOfExperience NUMBER,
	CHECK (level_Re BETWEEN 1 AND 6)
		 --1: Kem,
		 --2: Yeu,
		 --3: Trung binh,
		 --4: Kha,
		 --5: Gioi,
		 --6: Chuyen sau
);

--Khoa chinh
ALTER TABLE REQUIRE ADD CONSTRAINT PK_REQUIRE PRIMARY KEY (positionNo, requirementNo);

--Khoa ngoai
ALTER TABLE REQUIRE ADD CONSTRAINT FK1_REQUIRE FOREIGN KEY (positionNo) REFERENCES POSITION(positionNo);
ALTER TABLE REQUIRE ADD CONSTRAINT FK2_REQUIRE FOREIGN KEY (requirementNo) REFERENCES REQUIREMENT(requirementNo);

--Du lieu
Insert into REQUIRE (POSITIONNO,REQUIREMENTNO,LEVEL_RE,YEARSOFEXPERIENCE) values (1,3,2,null);
Insert into REQUIRE (POSITIONNO,REQUIREMENTNO,LEVEL_RE,YEARSOFEXPERIENCE) values (2,1,5,4);
Insert into REQUIRE (POSITIONNO,REQUIREMENTNO,LEVEL_RE,YEARSOFEXPERIENCE) values (5,4,6,null);
Insert into REQUIRE (POSITIONNO,REQUIREMENTNO,LEVEL_RE,YEARSOFEXPERIENCE) values (4,5,3,2);
Insert into REQUIRE (POSITIONNO,REQUIREMENTNO,LEVEL_RE,YEARSOFEXPERIENCE) values (3,2,4,1);
Insert into REQUIRE (POSITIONNO,REQUIREMENTNO,LEVEL_RE,YEARSOFEXPERIENCE) values (6,5,5,4);
Insert into REQUIRE (POSITIONNO,REQUIREMENTNO,LEVEL_RE,YEARSOFEXPERIENCE) values (7,5,5,6);
