package View;

import Process.Account;
import Process.AccountDao;
import Process.DataValidator;
import Process.MessageDialog;
import Process.SharedData;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Nguyen Anh Kiet
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNEWPASSWORD = new javax.swing.JPasswordField();
        txtCONFIRM = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtPASSWORD = new javax.swing.JPasswordField();
        btnChange = new javax.swing.JButton();
        btnUNDO = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHANGE PASSWORD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 6, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("New Password");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 138, -1));

        jLabel11.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Confirm New Password");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, -1));

        txtNEWPASSWORD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(txtNEWPASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 210, -1));

        txtCONFIRM.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(txtCONFIRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 210, -1));

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Current Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 138, -1));

        txtPASSWORD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPASSWORDActionPerformed(evt);
            }
        });
        getContentPane().add(txtPASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 210, -1));

        btnChange.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnChange.setText("Change Password");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        getContentPane().add(btnChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        btnUNDO.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnUNDO.setText("Back");
        btnUNDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUNDOActionPerformed(evt);
            }
        });
        getContentPane().add(btnUNDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/profilebg.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        AccountDao dao = new AccountDao();
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtPASSWORD, sb, "Password cannot be blank!");
        DataValidator.validateEmpty(txtNEWPASSWORD, sb, "New password cannot be blank!");
        DataValidator.validateEmpty(txtCONFIRM, sb, "You need to confirm password!");

        if (sb.length() > 0) {
            MessageDialog.showErrorDialog(this, sb.toString(), "Error");
            return;
        }

        String current = new String(txtPASSWORD.getPassword());
        String newpassword = new String(txtNEWPASSWORD.getPassword());
        String confirm = new String(txtCONFIRM.getPassword());

        try {
            if (!current.equals(dao.getPasswordByAccountID())) {
                MessageDialog.showErrorDialog(this, "The current password is invalid!", "Error");
                return;
            } else if (newpassword.length() < 8) {
                MessageDialog.showErrorDialog(this, "Password cannot be less than 8 characters!", "Error");
                return;
            }
        } catch (Exception e) {
            MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
        }

        if (newpassword.equals(confirm)) {
            int choose = MessageDialog.showConfirmDialog(this, "Do you sure want to change password?", "Confirm");
            if (choose == JOptionPane.YES_OPTION) {
                try {
                    Account a = new Account();

                    a.setUSERNAME(SharedData.useraccount.getUSERNAME());
                    a.setPASSWORD(newpassword);
                    a.setROLE(SharedData.useraccount.getROLE());

                    if (dao.update(a)) {
                        MessageDialog.showMessageDialog(this, "Password changed!", "Notification");
                    } else {
                        MessageDialog.showMessageDialog(this, "Update unsuccessfully!", "Notification");
                    }
                } catch (Exception e) {
                    MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
                }
            }

        } else {
            MessageDialog.showErrorDialog(this, "Those passwords did not match. Try again!", "Error");
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnUNDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUNDOActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();

        String role = SharedData.useraccount.getROLE();
        switch (role) {
            case "Công ty":
                frame = new CompanyFrame();
                break;
            case "Nhà tuyển dụng":
                frame = new InterviewerFrame();
                break;
            case "Ứng viên":
                frame = new ApplicantFrame();
                break;
            default:
                System.exit(0);
                break;
        }
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_btnUNDOActionPerformed

    private void txtPASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPASSWORDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnUNDO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtCONFIRM;
    private javax.swing.JPasswordField txtNEWPASSWORD;
    private javax.swing.JPasswordField txtPASSWORD;
    // End of variables declaration//GEN-END:variables
}
