package View;

import Process.Account;
import Process.AccountDao;
import Process.DataValidator;
import Process.MessageDialog;

/**
 *
 * @author acer
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnChange = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtUSERNAME = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rdbCOMPANY = new javax.swing.JRadioButton();
        rdbINTERVIEWER = new javax.swing.JRadioButton();
        rdbAPPLICANT = new javax.swing.JRadioButton();
        txtGMAIL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPASSWORD = new javax.swing.JPasswordField();
        txtCONFIRM = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnChange.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnChange.setText("Change Password");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        getContentPane().add(btnChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        btnUndo.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnUndo.setText("Back");
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });
        getContentPane().add(btnUndo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 162, -1));

        txtUSERNAME.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtUSERNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUSERNAMEActionPerformed(evt);
            }
        });
        getContentPane().add(txtUSERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 220, -1));

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Role");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 144, -1));

        buttonGroup1.add(rdbCOMPANY);
        rdbCOMPANY.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        rdbCOMPANY.setForeground(new java.awt.Color(255, 255, 255));
        rdbCOMPANY.setText("Company");
        getContentPane().add(rdbCOMPANY, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        buttonGroup1.add(rdbINTERVIEWER);
        rdbINTERVIEWER.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        rdbINTERVIEWER.setForeground(new java.awt.Color(255, 255, 255));
        rdbINTERVIEWER.setText("Recruiter");
        rdbINTERVIEWER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbINTERVIEWERActionPerformed(evt);
            }
        });
        getContentPane().add(rdbINTERVIEWER, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        buttonGroup1.add(rdbAPPLICANT);
        rdbAPPLICANT.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        rdbAPPLICANT.setForeground(new java.awt.Color(255, 255, 255));
        rdbAPPLICANT.setText("Candidate");
        getContentPane().add(rdbAPPLICANT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 90, -1));

        txtGMAIL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(txtGMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 220, -1));

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 162, -1));

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("New Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 162, -1));

        txtPASSWORD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(txtPASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 220, -1));

        txtCONFIRM.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(txtCONFIRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 220, -1));

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirm New Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Forgot Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/profilebg.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnUndoActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtUSERNAME, sb, "Username cannot be blank!");
        DataValidator.validateEmpty(txtPASSWORD, sb, "Password cannot be blank!");
        DataValidator.validateEmpty(txtCONFIRM, sb, "You need to confirm password!");

        if (sb.length() > 0) {
            MessageDialog.showErrorDialog(this, sb.toString(), "Error");
            return;
        }

        String password = new String(txtPASSWORD.getPassword());
        String confirm = new String(txtCONFIRM.getPassword());

        if (password.length() < 8) {
            MessageDialog.showErrorDialog(this, "Password cannot be less than 8 characters!", "Error");
            return;
        }

        String role;
        if (rdbCOMPANY.isSelected()) {
            role = "Công ty";
        } else if (rdbINTERVIEWER.isSelected()) {
            role = "Nhà tuyển dụng";
        } else {
            role = "Ứng viên";
        }

        AccountDao dao = new AccountDao();
        try {
            if (dao.checkForget(txtUSERNAME.getText(), role, txtGMAIL.getText())) {
                if (password.equals(confirm)) {
                    try {
                        Account a = new Account();

                        a.setUSERNAME(txtUSERNAME.getText());
                        a.setPASSWORD(new String(txtPASSWORD.getPassword()));
                        a.setROLE(role);

                        if (dao.update(a)) {
                            MessageDialog.showMessageDialog(this, "Password changed!", "Notification");
                        } else {
                            MessageDialog.showMessageDialog(this, "Changed unsuccesfully!", "Notification");
                        }
                    } catch (Exception e) {
                        MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
                    }
                } else {
                    MessageDialog.showErrorDialog(this, "Those passwords did not match. Try again.!", "Error");
                }
            } else {
                MessageDialog.showMessageDialog(this, "Information is invalid", "Notification");
            }
        } catch (Exception e) {
            MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    private void rdbINTERVIEWERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbINTERVIEWERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbINTERVIEWERActionPerformed

    private void txtUSERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUSERNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUSERNAMEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnUndo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton rdbAPPLICANT;
    private javax.swing.JRadioButton rdbCOMPANY;
    private javax.swing.JRadioButton rdbINTERVIEWER;
    private javax.swing.JPasswordField txtCONFIRM;
    private javax.swing.JTextField txtGMAIL;
    private javax.swing.JPasswordField txtPASSWORD;
    private javax.swing.JTextField txtUSERNAME;
    // End of variables declaration//GEN-END:variables
}
