package View;

import Process.Applicant;
import Process.ApplicantDao;
import Process.DataValidator;
import Process.MessageDialog;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class InformationApplicant extends javax.swing.JFrame {

    /**
     * Creates new form InformationApplicant
     */
    private Applicant a;
    private ApplicantDao dao;

    public InformationApplicant() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

        InThongTin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnUndo1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblAPPLICANTNO = new javax.swing.JLabel();
        lblAPPLICANTNAME = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCITIZENID = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDATEOFBIRTH = new javax.swing.JLabel();
        lblGENDER = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaADDRESS = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        txtPHONENUMBER = new javax.swing.JTextField();
        txtGMAIL = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("YOUR PROFILE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jButton1.setText("Update Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, -1, -1));

        btnUndo1.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnUndo1.setText("Back");
        btnUndo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndo1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnUndo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Candidate's ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, -1));

        lblAPPLICANTNO.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAPPLICANTNO.setForeground(new java.awt.Color(255, 255, 255));
        lblAPPLICANTNO.setText("(Trong)");
        getContentPane().add(lblAPPLICANTNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 240, -1));

        lblAPPLICANTNAME.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAPPLICANTNAME.setForeground(new java.awt.Color(255, 255, 255));
        lblAPPLICANTNAME.setText("(Trong)");
        getContentPane().add(lblAPPLICANTNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 240, -1));

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 83, -1));

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID Card Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, -1));

        lblCITIZENID.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCITIZENID.setForeground(new java.awt.Color(255, 255, 255));
        lblCITIZENID.setText("(Trong)");
        getContentPane().add(lblCITIZENID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 240, -1));

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date of Birth");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, -1));

        lblDATEOFBIRTH.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDATEOFBIRTH.setForeground(new java.awt.Color(255, 255, 255));
        lblDATEOFBIRTH.setText("(Trong)");
        getContentPane().add(lblDATEOFBIRTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 240, -1));

        lblGENDER.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblGENDER.setForeground(new java.awt.Color(255, 255, 255));
        lblGENDER.setText("(Trong)");
        getContentPane().add(lblGENDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 240, -1));

        jLabel9.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gender");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 83, -1));

        jLabel10.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Address");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 83, -1));

        txaADDRESS.setColumns(20);
        txaADDRESS.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txaADDRESS.setRows(5);
        jScrollPane1.setViewportView(txaADDRESS);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 240, 120));

        jLabel11.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Phone Number");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        txtPHONENUMBER.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(txtPHONENUMBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 420, 240, -1));

        txtGMAIL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(txtGMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 470, 240, -1));

        jLabel12.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Email");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 78, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/profilebg.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if (txaADDRESS.getText().equals("")) {
            MessageDialog.showErrorDialog(this, "Address cannot be blank!", "Error");
            return;
        } else if (txtPHONENUMBER.getText().equals("")) {
            MessageDialog.showErrorDialog(this, "Phone number cannot be blank!", "Error");
            return;
        } else if (!txtPHONENUMBER.getText().matches("\\d+")) {
            MessageDialog.showErrorDialog(this, "Phone number are numberous only!", "Error");
            return;
        } else if (txtPHONENUMBER.getText().length() != 10) {
            MessageDialog.showErrorDialog(this, "Phone number must be exactly 10 numbers!", "Error");
            return;
        } else if (txtGMAIL.getText().equals("")) {
            MessageDialog.showErrorDialog(this, "Email cannot be blank!", "Error");
            return;
        }

        DataValidator.validateGmail(txtGMAIL, sb, "Email must be formatted XXX@gmail.com");

        if (sb.length() > 0) {
            MessageDialog.showErrorDialog(this, sb.toString(), "Error");
            return;
        }

        int choose = MessageDialog.showConfirmDialog(this, "Do you sure want to update profile?", "Confirm");
        if (choose == JOptionPane.YES_OPTION) {
            try {
                a = new Applicant();
                dao = new ApplicantDao();

                a.setAPPLICANTNAME(lblAPPLICANTNAME.getText());
                a.setCITIZENID(lblCITIZENID.getText());
                java.sql.Date date = new java.sql.Date(new SimpleDateFormat("yyyy-MM-dd").parse(lblDATEOFBIRTH.getText()).getTime());
                a.setDATEOFBIRTH(date);
                a.setGENDER(lblGENDER.getText().equals("Nam") ? 0 : 1);
                a.setADDRESS(txaADDRESS.getText());
                a.setPHONENUMBER(txtPHONENUMBER.getText());
                a.setGMAIL(txtGMAIL.getText());

                if (dao.update(a)) {
                    MessageDialog.showMessageDialog(this, "Changed successfully!", "Notification");
                } else {
                    MessageDialog.showConfirmDialog(this, "Change unsuccessfully!", "Notification");
                }
            } catch (Exception e) {
                MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnUndo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndo1ActionPerformed
        // TODO add your handling code here:
        ApplicantFrame app = new ApplicantFrame();
        app.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnUndo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformationApplicant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformationApplicant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformationApplicant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformationApplicant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformationApplicant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUndo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAPPLICANTNAME;
    private javax.swing.JLabel lblAPPLICANTNO;
    private javax.swing.JLabel lblCITIZENID;
    private javax.swing.JLabel lblDATEOFBIRTH;
    private javax.swing.JLabel lblGENDER;
    private javax.swing.JTextArea txaADDRESS;
    private javax.swing.JTextField txtGMAIL;
    private javax.swing.JTextField txtPHONENUMBER;
    // End of variables declaration//GEN-END:variables

    private void InThongTin() {
        a = new Applicant();
        dao = new ApplicantDao();

        try {
            a = dao.getInformationByAccountID();
        } catch (Exception e) {
            MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
        }

        lblAPPLICANTNO.setText(String.valueOf(a.getAPPLICANTNO()));
        lblAPPLICANTNAME.setText(a.getAPPLICANTNAME());
        lblCITIZENID.setText(a.getCITIZENID());
        lblDATEOFBIRTH.setText(String.valueOf(a.getDATEOFBIRTH()));
        if (a.getGENDER() == 0) {
            lblGENDER.setText("Nam");
        } else {
            lblGENDER.setText("Nữ");
        }
        txaADDRESS.setText(a.getADDRESS());
        txtPHONENUMBER.setText(a.getPHONENUMBER());
        txtGMAIL.setText(a.getGMAIL());
    }
}
