package View;

import Process.Company;
import Process.CompanyDao;
import Process.DataValidator;
import Process.MessageDialog;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class InformationCompany extends javax.swing.JFrame {

    /**
     * Creates new form InformationCompany
     */
    private Company c;
    private CompanyDao dao;

    public InformationCompany() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        InThongTin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblCOMPANYNO = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCOMPANYNAME = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaADDRESS = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtHOTLINE = new javax.swing.JTextField();
        txtGMAIL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSTARTDATE = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COMPANY'S PROFILE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jButton2.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jButton2.setText("Profile Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 130, -1));

        jButton3.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Company ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, -1));

        lblCOMPANYNO.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCOMPANYNO.setForeground(new java.awt.Color(255, 255, 255));
        lblCOMPANYNO.setText("jLabel8");
        getContentPane().add(lblCOMPANYNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 240, -1));

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, -1));

        lblCOMPANYNAME.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCOMPANYNAME.setForeground(new java.awt.Color(255, 255, 255));
        lblCOMPANYNAME.setText("jLabel9");
        getContentPane().add(lblCOMPANYNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 240, -1));

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, -1));

        txaADDRESS.setColumns(20);
        txaADDRESS.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txaADDRESS.setRows(5);
        jScrollPane1.setViewportView(txaADDRESS);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 240, 120));

        jLabel5.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hotline");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, -1));

        txtHOTLINE.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(txtHOTLINE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 240, -1));

        txtGMAIL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(txtGMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 240, -1));

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 100, -1));

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Founding Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        lblSTARTDATE.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSTARTDATE.setForeground(new java.awt.Color(255, 255, 255));
        lblSTARTDATE.setText("jLabel10");
        getContentPane().add(lblSTARTDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 240, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/profilebg.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if (txaADDRESS.getText().equals("")) {
            MessageDialog.showErrorDialog(this, "Address cannot be blank!", "Error");
            return;
        } else if (txtHOTLINE.getText().equals("")) {
            MessageDialog.showErrorDialog(this, "Hotline cannot be blank!", "Error");
            return;
        } else if (!txtHOTLINE.getText().matches("\\d+")) {
            MessageDialog.showErrorDialog(this, "Hotline are numberous only!", "Error");
            return;
        } else if (txtHOTLINE.getText().length() != 10) {
            MessageDialog.showErrorDialog(this, "Hotline must be exactly 10 numbers!", "Error");
            return;
        } else if (txtGMAIL.getText().equals("")) {
            MessageDialog.showErrorDialog(this, "Email cannot be blank!", "Error");
            return;
        }

        DataValidator.validateGmail(txtGMAIL, sb, "Email must be formatted XXX@gmail.com");

        if (sb.length() > 0) {
            MessageDialog.showErrorDialog(this, sb.toString(), "Lỗi");
            return;
        }

        int choose = MessageDialog.showConfirmDialog(this, "Do you sure want to update profile?", "Confirm");
        if (choose == JOptionPane.YES_OPTION) {
            try {
                c = new Company();
                dao = new CompanyDao();
                
                c.setCOMPANYNAME(lblCOMPANYNAME.getText());
                c.setADDRESS(txaADDRESS.getText());
                c.setHOTLINE(txtHOTLINE.getText());
                c.setGMAIL(txtGMAIL.getText());
                java.sql.Date date = new java.sql.Date(new SimpleDateFormat("yyyy-MM-dd").parse(lblSTARTDATE.getText()).getTime());
                c.setSTARTDATE(date);

                if (dao.update(c)) {
                    MessageDialog.showMessageDialog(this, "Changed successfully!", "Notification");
                } else {
                    MessageDialog.showConfirmDialog(this, "Change unsuccessfully!", "Notification");
                }
            } catch (Exception e) {
                MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CompanyFrame cf = new CompanyFrame();
        cf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformationCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformationCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformationCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformationCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformationCompany().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCOMPANYNAME;
    private javax.swing.JLabel lblCOMPANYNO;
    private javax.swing.JLabel lblSTARTDATE;
    private javax.swing.JTextArea txaADDRESS;
    private javax.swing.JTextField txtGMAIL;
    private javax.swing.JTextField txtHOTLINE;
    // End of variables declaration//GEN-END:variables

    private void InThongTin() {
        c = new Company();
        dao = new CompanyDao();

        try {
            c = dao.getInformationByAccountID();
        } catch (Exception e) {
            MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
        }

        lblCOMPANYNO.setText(String.valueOf(c.getCOMPANYNO()));
        lblCOMPANYNAME.setText(c.getCOMPANYNAME());
        txaADDRESS.setText(c.getADDRESS());
        txtHOTLINE.setText(c.getHOTLINE());
        txtGMAIL.setText(c.getGMAIL());
        lblSTARTDATE.setText(String.valueOf(c.getSTARTDATE()));
    }
}
