package View;

import Process.DataValidator;
import Process.Evaluate;
import Process.EvaluateDao;
import Process.MessageDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class NotEvaluateAPL extends javax.swing.JDialog {

    /**
     * Creates new form NotEvaluateAPL
     */
    private int APPLICANTNO, INTERVIEWSCHEDULENO;

    /**
     * Creates new form NotEvaluateAPL
     */
    public NotEvaluateAPL(java.awt.Frame parent, boolean modal, int maApp, int maITS) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

        APPLICANTNO = maApp;
        INTERVIEWSCHEDULENO = maITS;

        lblINTERVIEWSCHEDULE.setText(String.valueOf(INTERVIEWSCHEDULENO));
        lblAPPLICANTNO.setText(String.valueOf(APPLICANTNO));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMARK = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaCOMMENT = new javax.swing.JTextArea();
        lblAPPLICANTNO = new javax.swing.JLabel();
        lblINTERVIEWSCHEDULE = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rate Candidate");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Interview ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 129, -1));

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Candidate ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 129, -1));

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rating");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 129, -1));

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Review");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 129, -1));

        txtMARK.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(txtMARK, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 250, -1));

        txaCOMMENT.setColumns(20);
        txaCOMMENT.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txaCOMMENT.setRows(5);
        jScrollPane1.setViewportView(txaCOMMENT);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 250, -1));

        lblAPPLICANTNO.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAPPLICANTNO.setForeground(new java.awt.Color(255, 255, 255));
        lblAPPLICANTNO.setText("jLabel5");
        getContentPane().add(lblAPPLICANTNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 250, -1));

        lblINTERVIEWSCHEDULE.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblINTERVIEWSCHEDULE.setForeground(new java.awt.Color(255, 255, 255));
        lblINTERVIEWSCHEDULE.setText("jLabel6");
        getContentPane().add(lblINTERVIEWSCHEDULE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 250, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/profilebg.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int diem = Integer.parseInt(txtMARK.getText());
        if (txtMARK.getText().equals("")) {
            MessageDialog.showErrorDialog(this, "Rating cannot be blank!", "Error");
            return;
        } else if (txtMARK.getText().length() > 0 && !txtMARK.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Rating are numberous only!");
            return;
        } else if (diem < 1 || diem > 5 ) {
            JOptionPane.showMessageDialog(this, "Rating can only be on the scale 1 - 5!");
            return;
        }

        try {
            EvaluateDao dao = new EvaluateDao();
            int mark_apl = Integer.parseInt(txtMARK.getText());
            String comment_apl = txaCOMMENT.getText();
            Evaluate ev = new Evaluate(mark_apl, comment_apl);

            if (dao.insertEvaluateAPL(APPLICANTNO, INTERVIEWSCHEDULENO, ev)) {
                MessageDialog.showMessageDialog(this, "Added successfully!", "Notification");
                this.dispose();
            } else {
                MessageDialog.showConfirmDialog(this, "Add unsuccessfully!", "Notification");
            }
        } catch (Exception e) {
            MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAPPLICANTNO;
    private javax.swing.JLabel lblINTERVIEWSCHEDULE;
    private javax.swing.JTextArea txaCOMMENT;
    private javax.swing.JTextField txtMARK;
    // End of variables declaration//GEN-END:variables
}
