package View;

import java.sql.*;
import ConnectDB.ConnectOracle;
import Process.Company;
import Process.CompanyDao;
import Process.Department;
import Process.InterviewSchedule;
import Process.MessageDialog;
import Process.Position;
import Process.RecruitDao;
import Process.Require;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author acer
 */
public class RegisterSchedule extends javax.swing.JFrame {

    /**
     * Creates new form RegisterSchedule
     */
    private DefaultTableModel modelRequire;
    private DefaultTableModel modelLPV;
    private int maLich, maPhong, maViTri;
    private String tenCty;

    public RegisterSchedule(String COMPANYNAME, String DEPARTMENTNAME,
            String POSITIONNAME) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

        modelRequire = (DefaultTableModel) tblREQUIRE.getModel();
        modelLPV = (DefaultTableModel) tblINTERVIEW_SCHEDULE.getModel();
        Load(COMPANYNAME, DEPARTMENTNAME, POSITIONNAME);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblDEPARTMENTNAME = new javax.swing.JLabel();
        lblSTARTDATE = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblGMAIL = new javax.swing.JLabel();
        lblHOTLINE = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblADDRESS = new javax.swing.JLabel();
        lblCOMPANYNAME = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblPOSITIONNAME = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblREQUIRE = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblINTERVIEW_SCHEDULE = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Job Description");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 630, -1, -1));

        jButton2.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, -1, -1));

        jButton3.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jButton3.setText("Company's Reviews");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 102));
        jLabel13.setText("Department Information");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Name");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, -1));

        lblDEPARTMENTNAME.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDEPARTMENTNAME.setForeground(new java.awt.Color(255, 255, 255));
        lblDEPARTMENTNAME.setText("jLabel16");
        getContentPane().add(lblDEPARTMENTNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 200, -1));

        lblSTARTDATE.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSTARTDATE.setForeground(new java.awt.Color(255, 255, 255));
        lblSTARTDATE.setText("jLabel12");
        getContentPane().add(lblSTARTDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 200, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Founding Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 100, -1));

        lblGMAIL.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblGMAIL.setForeground(new java.awt.Color(255, 255, 255));
        lblGMAIL.setText("jLabel11");
        getContentPane().add(lblGMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 720, -1));

        lblHOTLINE.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHOTLINE.setForeground(new java.awt.Color(255, 255, 255));
        lblHOTLINE.setText("jLabel10");
        getContentPane().add(lblHOTLINE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 200, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hotline");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 100, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 100, -1));

        lblADDRESS.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblADDRESS.setForeground(new java.awt.Color(255, 255, 255));
        lblADDRESS.setText("jLabel9");
        getContentPane().add(lblADDRESS, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 720, -1));

        lblCOMPANYNAME.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCOMPANYNAME.setForeground(new java.awt.Color(255, 255, 255));
        lblCOMPANYNAME.setText("jLabel8");
        getContentPane().add(lblCOMPANYNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 200, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 100, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Company Information");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Position");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lblPOSITIONNAME.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPOSITIONNAME.setForeground(new java.awt.Color(255, 255, 255));
        lblPOSITIONNAME.setText("jLabel16");
        getContentPane().add(lblPOSITIONNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 220, -1));

        tblREQUIRE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblREQUIRE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Requirement", "Expertise Level", "Years Of Experience"
            }
        ));
        jScrollPane1.setViewportView(tblREQUIRE);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 360, 160));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 102));
        jLabel18.setText("Position Information");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 102));
        jLabel20.setText("Interview Schedule");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        tblINTERVIEW_SCHEDULE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblINTERVIEW_SCHEDULE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Interview ID", "Start Date", "End Date", "Location", "Limited Candidate"
            }
        ));
        tblINTERVIEW_SCHEDULE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblINTERVIEW_SCHEDULEMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblINTERVIEW_SCHEDULE);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 470, 160));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/profilebg2.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, -50, 1130, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblINTERVIEW_SCHEDULEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblINTERVIEW_SCHEDULEMouseClicked
        // TODO add your handling code here:
        int row = tblINTERVIEW_SCHEDULE.getSelectedRow();

        if (row >= 0) {
            int id = (int) tblINTERVIEW_SCHEDULE.getValueAt(row, 0);
            maLich = id;
        }
    }//GEN-LAST:event_tblINTERVIEW_SCHEDULEMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SearchJob sj = new SearchJob();
        sj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int choose = MessageDialog.showConfirmDialog(this, "Do you want to register interview schedule?", "Confirm");
        if (choose == JOptionPane.YES_OPTION) {
            try {
                RecruitDao dao = new RecruitDao();
                if (dao.Register(maLich, maPhong, maViTri)) {
                    MessageDialog.showMessageDialog(this, "Registered successfully!", "Notification");
                    LoadSchedule(dao, tenCty);
                } else {
                    MessageDialog.showConfirmDialog(this, "Register unsuccessfully!", "Notification");
                }
            } catch (Exception e) {
                MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CompanyDao dao = new CompanyDao();
        int companyno = 0;
        try {
            companyno = dao.getCompanyNoByCompanyName(tenCty);
        } catch (Exception e) {
            MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
        }

        try {
            Connection con = ConnectOracle.openConnection();
            String s = "src/Resource/EvaluateCompany.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(s);
            HashMap hs = new HashMap();
            hs.put("MaCongTy", companyno);
            JasperPrint jp = JasperFillManager.fillReport(jr, hs, con);
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblADDRESS;
    private javax.swing.JLabel lblCOMPANYNAME;
    private javax.swing.JLabel lblDEPARTMENTNAME;
    private javax.swing.JLabel lblGMAIL;
    private javax.swing.JLabel lblHOTLINE;
    private javax.swing.JLabel lblPOSITIONNAME;
    private javax.swing.JLabel lblSTARTDATE;
    private javax.swing.JTable tblINTERVIEW_SCHEDULE;
    private javax.swing.JTable tblREQUIRE;
    // End of variables declaration//GEN-END:variables

    private void Load(String COMPANYNAME, String DEPARTMENTNAME, String POSITIONNAME) {
        RecruitDao dao = new RecruitDao();

        LoadCompany(dao, COMPANYNAME);

        LoadDepartment(dao, DEPARTMENTNAME);

        LoadPosition(dao, POSITIONNAME, COMPANYNAME, DEPARTMENTNAME);

        LoadSchedule(dao, COMPANYNAME);
    }

    private void LoadCompany(RecruitDao dao, String COMPANYNAME) {
        Company c;
        try {
            c = dao.InformationCompany(COMPANYNAME);
            lblCOMPANYNAME.setText(c.getCOMPANYNAME());
            lblADDRESS.setText(c.getADDRESS());
            lblHOTLINE.setText(c.getHOTLINE());
            lblGMAIL.setText(c.getGMAIL());
            lblSTARTDATE.setText(String.valueOf(c.getSTARTDATE()));

            tenCty = c.getCOMPANYNAME();
        } catch (Exception e) {
            MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
        }
    }

    private void LoadDepartment(RecruitDao dao, String DEPARTMENTNAME) {
        Department d;
        try {
            d = dao.InformationDepartment(DEPARTMENTNAME);
            lblDEPARTMENTNAME.setText(d.getDEPARTMENTNAME());

            maPhong = d.getDEPARTMENTNO();
        } catch (Exception e) {
            MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
        }
    }

    private void LoadPosition(RecruitDao dao, String POSITIONNAME,
            String COMPANYNAME, String DEPARTMENTNAME) {
        Position p;
        try {
            p = dao.InformationPosition(POSITIONNAME);
            lblPOSITIONNAME.setText(p.getPOSITIONNAME());

            maViTri = p.getPOSITIONNO();
        } catch (Exception e) {
            MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
        }
        try {
            List<Require> list = dao.findRequire(COMPANYNAME, DEPARTMENTNAME, POSITIONNAME);
            modelRequire.setRowCount(0);
            for (Require x : list) {
                String trinhdo;
                int level = x.getLEVEL_RE();
                switch (level) {
                    case 1:
                        trinhdo = "No Experience";
                        break;
                    case 2:
                        trinhdo = "Beginner";
                        break;
                    case 3:
                        trinhdo = "Familiar";
                        break;
                    case 4:
                        trinhdo = "Intermediate";
                        break;
                    case 5:
                        trinhdo = "Advance";
                        break;
                    default:
                        trinhdo = "Expert";
                        break;
                }
                modelRequire.addRow(new Object[]{
                    x.getREQUIREMENTNAME(), trinhdo, x.getYEARSOFEXPERIENCE()});
            }

            modelRequire.fireTableDataChanged();
            tblREQUIRE.setModel(modelRequire);
        } catch (Exception e) {
            MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
        }
    }

    private void LoadSchedule(RecruitDao dao, String COMPANYNAME) {
        try {
            List<InterviewSchedule> list = dao.findSchedule(COMPANYNAME);
            modelLPV.setRowCount(0);
            for (InterviewSchedule x : list) {
                if (x.getSLOT() > 0 && x.getSTATUS() == 0) {
                    modelLPV.addRow(new Object[]{
                        x.getINTERVIEWSCHEDULENO(), x.getSTARTTIME(), x.getENDTIME(),
                        x.getLOCATION(), x.getSLOT()});
                }
            }
            modelLPV.fireTableDataChanged();
            tblINTERVIEW_SCHEDULE.setModel(modelLPV);
        } catch (Exception e) {
            MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
        }
    }
}
