package View;

import Process.Account;
import Process.AccountDao;
import Process.Company;
import Process.CompanyDao;
import Process.DataValidator;
import Process.MessageDialog;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class RegisterCompany extends javax.swing.JFrame {

    /**
     * Creates new form RegisterCompany
     */
    public RegisterCompany() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCOMPANYNAME = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaADDRESS = new javax.swing.JTextArea();
        txtHOTLINE = new javax.swing.JTextField();
        txtGMAIL = new javax.swing.JTextField();
        dtSTARTDATE = new com.toedter.calendar.JDateChooser();
        txtUSERNAME = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        txtPASSWORD = new javax.swing.JPasswordField();
        txtCONFIRM = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jLabel2.setText("Company name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 124, -1));

        jLabel6.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 124, -1));

        jLabel3.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jLabel3.setText("Hotline");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 124, -1));

        jLabel8.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jLabel8.setText("Gmail");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 124, -1));

        jLabel4.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jLabel4.setText("Founding date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 124, -1));

        jLabel9.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jLabel9.setText("Username");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 124, -1));

        jLabel10.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jLabel10.setText("Password");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 124, -1));

        jLabel11.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jLabel11.setText("Confirm password");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, -1, -1));

        txtCOMPANYNAME.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtCOMPANYNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 220, -1));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(272, 104));

        txaADDRESS.setColumns(20);
        txaADDRESS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txaADDRESS.setRows(5);
        jScrollPane1.setViewportView(txaADDRESS);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 220, -1));

        txtHOTLINE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtHOTLINE, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 220, -1));

        txtGMAIL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtGMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 220, -1));

        dtSTARTDATE.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        getContentPane().add(dtSTARTDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 150, -1));

        txtUSERNAME.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUSERNAME.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUSERNAMEFocusLost(evt);
            }
        });
        getContentPane().add(txtUSERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 220, -1));

        btnRegister.setBackground(new java.awt.Color(79, 220, 194));
        btnRegister.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Sign Up");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, -1, -1));

        btnUndo.setBackground(new java.awt.Color(79, 220, 194));
        btnUndo.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        btnUndo.setForeground(new java.awt.Color(255, 255, 255));
        btnUndo.setText("Back");
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });
        getContentPane().add(btnUndo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 630, -1, -1));

        txtPASSWORD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtPASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 220, -1));

        txtCONFIRM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtCONFIRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 220, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/dangky.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        // TODO add your handling code here:
        ChooseRole cr = new ChooseRole();
        cr.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnUndoActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        String password = new String(txtPASSWORD.getPassword());
        String confirm = new String(txtCONFIRM.getPassword());

        if (txtCOMPANYNAME.getText().equals("")) {
            MessageDialog.showErrorDialog(this, "Company cannot be blank!", "Error");
            return;
        } else if (txaADDRESS.getText().equals("")) {
            MessageDialog.showErrorDialog(this, "Address cannot be blank!", "Error");
            return;
        } else if (txtHOTLINE.getText().equals("")) {
            MessageDialog.showErrorDialog(this, "Hotline cannot be blank!", "Error");
            return;
        } else if (!txtHOTLINE.getText().matches("\\d+")) {
            MessageDialog.showErrorDialog(this, "Hotline are numberous only!", "Error");
            return;
        } else if (txtHOTLINE.getText().length() != 10) {
            MessageDialog.showErrorDialog(this, "Hotline must be exactly 10 numbers!", "Error");
            return;
        }else if (txtGMAIL.getText().equals("")) {
            MessageDialog.showErrorDialog(this, "Email cannot be blank!", "Error");
            return;
        } else if (txtUSERNAME.getText().equals("")) {
            MessageDialog.showErrorDialog(this, "Username cannot be blank!", "Error");
            return;
        } else if (password.length() < 8) {
            MessageDialog.showErrorDialog(this, "Password cannot be less than 8 characters!", "Error");
            return;
        }

        DataValidator.validateEmpty(txtPASSWORD, sb, "Password cannot be blank!");
        DataValidator.validateEmpty(txtCONFIRM, sb, "You need to confirm password!");
        DataValidator.validateGmail(txtGMAIL, sb, "Email must be formatted XXX@gmail.com");

        if (sb.length() > 0) {
            MessageDialog.showErrorDialog(this, sb.toString(), "Error");
            return;
        }

        if (password.equals(confirm)) {
            int choose = MessageDialog.showConfirmDialog(this, "Do you want to create new account?", "Confirm");
            if (choose == JOptionPane.YES_OPTION) {
                try {
                    Account a = new Account();

                    a.setUSERNAME(txtUSERNAME.getText());
                    a.setPASSWORD(new String(txtPASSWORD.getPassword()));
                    a.setROLE("Công ty");

                    AccountDao dao = new AccountDao();
                    if (dao.insert(a)) {
                        int accountid = dao.getAccountIDByUsername(a.getUSERNAME());
                        Date startdate = new Date(dtSTARTDATE.getDate().getTime());
                        Company c = new Company();

                        c.setCOMPANYNAME(txtCOMPANYNAME.getText());
                        c.setADDRESS(txaADDRESS.getText());
                        c.setHOTLINE(txtHOTLINE.getText());
                        c.setGMAIL(txtGMAIL.getText());
                        c.setSTARTDATE(startdate);
                        c.setACCOUNTID(accountid);

                        CompanyDao cdao = new CompanyDao();
                        if (cdao.insert(c)) {
                            MessageDialog.showMessageDialog(this, "Created successfully!", "Notification");
                        } else {
                            MessageDialog.showConfirmDialog(this, "Create unsuccessfully!", "Notification");
                        }
                    } else {
                        MessageDialog.showConfirmDialog(this, "Create unsuccessfully!", "Notification");
                    }
                } catch (Exception e) {
                    MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
                }
            }
        } else {
            MessageDialog.showErrorDialog(this, "Those passwords did not match. Try again!", "Error");
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtUSERNAMEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUSERNAMEFocusLost
        // TODO add your handling code here:
        AccountDao dao = new AccountDao();
        try {
            if(dao.checkUsername(txtUSERNAME.getText())) {
                MessageDialog.showErrorDialog(this, "Username available", "Error");
            }
        } catch (Exception e) {
            MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
        }
    }//GEN-LAST:event_txtUSERNAMEFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterCompany().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnUndo;
    private com.toedter.calendar.JDateChooser dtSTARTDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaADDRESS;
    private javax.swing.JTextField txtCOMPANYNAME;
    private javax.swing.JPasswordField txtCONFIRM;
    private javax.swing.JTextField txtGMAIL;
    private javax.swing.JTextField txtHOTLINE;
    private javax.swing.JPasswordField txtPASSWORD;
    private javax.swing.JTextField txtUSERNAME;
    // End of variables declaration//GEN-END:variables
}
