package View;

import Process.InterviewSchedule;
import Process.InterviewScheduleDao;
import Process.MessageDialog;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class RMSchedule extends javax.swing.JDialog {

    /**
     * Creates new form RMSchedule
     */
    private DefaultTableModel model;
    
    public RMSchedule(java.awt.Frame parent, boolean modal, int maITV) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        
        model = (DefaultTableModel) tblSCHEDULE.getModel();
        LoadData(maITV);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSCHEDULE = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Interview Schedule List");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 6, -1, -1));

        tblSCHEDULE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSCHEDULE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Start Date", "End Date", "Location", "Status", "Maximum Candidate"
            }
        ));
        tblSCHEDULE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSCHEDULEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSCHEDULE);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 701, 323));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/profilebg2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSCHEDULEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSCHEDULEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSCHEDULEMouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSCHEDULE;
    // End of variables declaration//GEN-END:variables

    private void LoadData(int maITV) {
        try {
            InterviewScheduleDao dao = new InterviewScheduleDao();
            List<InterviewSchedule> list = dao.findListByInterviewerNo(maITV);
            model.setRowCount(0);
            for (InterviewSchedule x : list) {
                String trangthai;
                if (x.getSTATUS() == 0) {
                    trangthai = "Incompleted";
                } else {
                    trangthai = "Completed";
                }

                model.addRow(new Object[]{
                    x.getINTERVIEWSCHEDULENO(), x.getSTARTTIME(), x.getENDTIME(),
                    x.getLOCATION(), trangthai, x.getSLOT()});
            }
            model.fireTableDataChanged();
            tblSCHEDULE.setModel(model);
        } catch (Exception e) {
            MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
        }
    }
}
