package View;

import ConnectDB.ConnectOracle;
import java.sql.*;
import Process.Applicant;
import Process.ApplicantDao;
import Process.HaveSkill;
import Process.HaveSkillDao;
import Process.MessageDialog;
import java.util.HashMap;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author acer
 */
public class SeeCandidate extends javax.swing.JDialog {

    /**
     * Creates new form SeeCandidate
     */
    private DefaultTableModel model;
    private int maUV;
    private Connection con;

    public SeeCandidate(java.awt.Frame parent, boolean modal, int maApp) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

        maUV = maApp;
        model = (DefaultTableModel) tblSKILL.getModel();
        InThongTin(maApp);
        LoadData(maApp);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSKILL = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblGMAIL = new javax.swing.JLabel();
        lblPHONENUMBER = new javax.swing.JLabel();
        lblAPPLICANTNAME = new javax.swing.JLabel();
        lblAPPLICANTNO = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSKILL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSKILL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Expertise Level", "Years Of Experience"
            }
        ));
        jScrollPane1.setViewportView(tblSKILL);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 440, 180));

        jLabel11.setFont(new java.awt.Font("Dubai", 3, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 153));
        jLabel11.setText("Candidate Skill");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 110, -1));

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Candidate Information");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jButton4.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jButton4.setText("Candidate's Reviews");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dubai", 3, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Personal Information");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, -1));

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Candidate ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, -1));

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, -1));

        jLabel5.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 110, -1));

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, -1));

        lblGMAIL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblGMAIL.setForeground(new java.awt.Color(255, 255, 255));
        lblGMAIL.setText("jLabel10");
        getContentPane().add(lblGMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 300, -1));

        lblPHONENUMBER.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPHONENUMBER.setForeground(new java.awt.Color(255, 255, 255));
        lblPHONENUMBER.setText("jLabel9");
        getContentPane().add(lblPHONENUMBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 300, -1));

        lblAPPLICANTNAME.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAPPLICANTNAME.setForeground(new java.awt.Color(255, 255, 255));
        lblAPPLICANTNAME.setText("jLabel8");
        getContentPane().add(lblAPPLICANTNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 300, -1));

        lblAPPLICANTNO.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAPPLICANTNO.setForeground(new java.awt.Color(255, 255, 255));
        lblAPPLICANTNO.setText("jLabel7");
        getContentPane().add(lblAPPLICANTNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 300, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/profilebg2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-360, 0, 840, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            con = ConnectOracle.openConnection();
            String s = "src/Resource/EvaluateApplicant.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(s);
            HashMap hs = new HashMap();
            hs.put("MaUngVien", maUV);
            JasperPrint jp = JasperFillManager.fillReport(jr, hs, con);
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
        }
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAPPLICANTNAME;
    private javax.swing.JLabel lblAPPLICANTNO;
    private javax.swing.JLabel lblGMAIL;
    private javax.swing.JLabel lblPHONENUMBER;
    private javax.swing.JTable tblSKILL;
    // End of variables declaration//GEN-END:variables

    private void InThongTin(int maApp) {
        Applicant a = new Applicant();
        ApplicantDao dao = new ApplicantDao();

        try {
            a = dao.getInformationAPL(maApp);
        } catch (Exception e) {
            MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
        }

        lblAPPLICANTNO.setText(String.valueOf(a.getAPPLICANTNO()));
        lblAPPLICANTNAME.setText(a.getAPPLICANTNAME());
        lblPHONENUMBER.setText(a.getPHONENUMBER());
        lblGMAIL.setText(a.getGMAIL());
    }

    private void LoadData(int maApp) {
        try {
            HaveSkillDao dao = new HaveSkillDao();
            List<HaveSkill> list = dao.findSkill(maApp);
            model.setRowCount(0);
            for (HaveSkill x : list) {
                String trinhdo;
                switch (x.getLEVEL_APL()) {
                    case 1:
                        trinhdo = "No Experience";
                        break;
                    case 2:
                        trinhdo = "Beginner";
                        break;
                    case 3:
                        trinhdo = "Familiar";
                        break;
                    case 4:
                        trinhdo = "Intermediate";
                        break;
                    case 5:
                        trinhdo = "Advance";
                        break;
                    default:
                        trinhdo = "Expert";
                        break;
                }

                model.addRow(new Object[]{
                    x.getSKILLNAME(), trinhdo, x.getYEARSOFEXPERIENCE()});
            }

            model.fireTableDataChanged();
            tblSKILL.setModel(model);

        } catch (Exception e) {
            MessageDialog.showErrorDialog(this, e.getMessage(), "Error");
        }
    }
}
